### ISSUE TITLE
How to solve this err？

### ISSUE THREAD

**Issue by cooper1x** [shime/play-sound#25]
`C:\Users\Cooper\Desktop\pp\app.js:5
    if (err) throw err
             ^

Error: Couldn't find a suitable audio player
    at Play.play (C:\Users\Cooper\node_modules\play-sound\index.js:34:19)
    at Object.<anonymous> (C:\Users\Cooper\Desktop\pp\app.js:4:8)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3`

**Comment by shime** [comment]
Looks like you don't have any audio player installed. Try installing an audio player first.
